#!/bin/bash

reset=0

LevelGPU=-1
LevelMEMORY=-1

SetLevelGPU=-1
SetLevelMEMORY=-1

ClockGPU=0
ClockMEMORY=0

VoltageGPU=0
VoltageMEMORY=0

opts=0

while getopts rL:C:V:l:c:v:P:p: option
do
	opts=1
	case "${option}"
	in
	r) reset=1;;
	L) LevelGPU=${OPTARG};;
	C) ClockGPU=${OPTARG};;
	V) VoltageGPU=${OPTARG};;
	l) LevelMEMORY=${OPTARG};;
	c) ClockMEMORY=${OPTARG};;
	v) VoltageMEMORY=${OPTARG};;
	P) SetLevelGPU=${OPTARG};;
	p) SetLevelMEMORY=${OPTARG};;
	esac
done

# Show table
if [ $opts -eq 0 ]
then
  rocm-smi -S
  exit 1
fi

# Reset table
if [ $reset -eq 1 ]
then
  rocm-smi -r
  exit 1
fi

# Edit Power Play Table
# GPU Core
if [ $LevelGPU != -1 ]
then
	echo "Setting GPU level to $LevelGPU $ClockGPU $VoltageGPU"
	rocm-smi --setslevel $LevelGPU $ClockGPU $VoltageGPU
	expect "Do you accept these terms? [y/N]"
	send "y"
fi
# GPU Memory
if [ $LevelMEMORY != -1 ]
then
	echo "Setting MEMORY level to $LevelGPU $ClockGPU $VoltageGPU"
	rocm-smi --setmlevel $LevelMEMORY $ClockMEMORY $VoltageMEMORY  
	expect "Do you accept these terms? [y/N]"
	send "y"
fi

# Set Manual Performance Level
# GPU Core
if [ $SetLevelGPU != -1 ]
then
	rocm-smi --setperflevel manual
	echo "Setting GPU Core level to $SetLevelGPU"
	rocm-smi --setsclk $SetLevelGPU
fi

# GPU Core
if [ $SetLevelMEMORY != -1 ]
then
	rocm-smi --setperflevel manual
	echo "Setting GPU Memory level to $SetLevelMEMORY"
	rocm-smi --setmclk $SetLevelMEMORY
fi